# Pytorch tutorial 시작

## 1. Tensor란 무엇인가.
https://pytorch.org/tutorials/beginner/basics/tensor_tutorial.html

tensor는 list, tuple과 같은 하나의 Data structure이다.  
파이토치에서는 tensor를 사용하여 model의 input, output, parameter를 encode하게 된다.  

Pytorch의 특징:
1. GPU에 올려서 실행할 수 있다.
2. data를 카피할 필요도 없다.
3. 자동 미분에 최적화 되어있다. (자동 미분관련하여 자세한 것은 [Autograd section 참고](https://pytorch.org/tutorials/beginner/basics/autograd_tutorial.html))

In [1]:
import torch
import numpy as np

`-` tensor는 numpy array로부터 변환 가능하다.

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data) # List로부터 tensor 만들기
np_array = np.array(x_data) # tensor로부터 ndarray 만들기
x_np = torch.from_numpy(np_array) # ndarray로부터 tensor 만들기

`-` shape와 datatype만 가져와 새로운 텐서를 만들수도 있다.  
아래의 x_ones는 x_data의 shape와 datatype(**dtype**이라고도 한다.)을 가진 1로 이루어진 tensor를 생성한다.  
x_rand는 x_data의 shape를 유지하면서 dtype이 torch.float인 랜덤 tensor들을 생성한다.

In [3]:
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.4499, 0.4079],
        [0.2207, 0.6538]])


`-` tensor.shape에서 shape는 tensor의 dimension을 나타내는 tuple 데이터이다.  
아래 결과는 shape를 지정하여 tensor를 생성하는 것을 나타낸다.

In [9]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6251, 0.8828, 0.4285],
        [0.4402, 0.0465, 0.5327]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


`-` Tensor의 Attribute:  
Tensor의 Attributes는 `shape`, `dtype(datatype)` 그리고 tensor가 저장되어있는 device를 나타내는 것이다.  
아래는 torch.tensor에 귀속되어있는 attributes인 shape, dtypes, device의 출력 결과를 나타낸다.

In [4]:
tensor = torch.rand(3,4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


`-` Tensor에서의 연산  
Tensor에는 100가지가 넘는 연산자들이 존재한다.
- 연산자 예: arithmetic, linear algebra, matrix manipulation(transposing, indexing, slicing), sampling 등등

각각의 연산들은 GPU상에서 실행될 수 있다.
- **보통 GPU위에서의 연산이 CPU에서의 연산보다 빠르다.**

Default로, tensor를 생성하면 CPU위에서 생성된다. 따라서, GPU위에 tensor data를 올리려면 GPU가 사용 가능한지 확인한 후, `.to` method를 사용해서 올릴 수 있다.  
- **device간에 크기가 큰 tensor를 copy하는 것은 시간과 메모리 상에서 expensive함을 명심하자!**

In [11]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

`-` Tensor의 indexing을 살펴보자  
- 첫 번째 row는 [0]으로 가르킨다.
- 첫 번쨰 col은 [:,0]으로 가르킨다.
- 마지막 column은 [..., -1]로 가르킨다.
    - 여기서 ...은 `ELLIPSIS`라고 하는 객체이다. 이는, 다차원 데이터 배열을 쉽게 처리할 수 있도록 하는 것이다. 필자는 깊게 확인하지 않았는데, 예시 관련해서는 (https://whereisend.tistory.com/221) 참고.

In [5]:
tensor = torch.ones(4, 4) # 2차원 텐서에 대해서,
print('First row: ',tensor[0]) # 첫 번째 row는 [0]으로 가르킨다.
print('First column: ', tensor[:, 0]) # 첫 번쨰 col은 [:,0]으로 가르킨다
print('Last column:', tensor[..., -1]) # 마지막 column은 [..., -1]로 가르킨다.
tensor[:,1] = 0 # 이는 point wise와 같이 0을 넣으면 해당 column이 모두 0이 되는 것이다.
print(tensor)


First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


`-` Tensor 여러개 결합하기:  
Tensor 여러개 결합은 cat이라는 concatenate 기능을 하는 함수를 통해서 결합할 수 있다.  
아래에서는 tensor 데이터 여러개를 cat을 하고, 어떤 방향으로 결합할지는 dim이라는 인자로 지정하는데, 여기선 첫번쨰 차원에 대해서 결합하고자 dim=1를 사용했다.

In [7]:
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


`-` 산술 연산  
아래의 3개 연산은 모두 같은 matrix 곱을 나타낸다. 모두 결과는 같다.

In [8]:
y1 = tensor @ tensor.T # matrix 곱을 의미한다.
y2 = tensor.matmul(tensor.T) # 마찬가지로 matrix 곱을 의미한다.

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3) # 역시 matrix 곱이다. out인자의 역할은 잘 모르겠다.

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

곱의 형태를 자세히 파악하기 위해 아래와 같이, row, column의 개수가 서로 다른 경우를 보자. 아래는 2 by 5 matrix이다.

In [12]:
tensor = torch.tensor([[1,2,3,4,5],[6,7,8,9,10]])
tensor

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [15]:
print(tensor.shape), print(tensor.T.shape)
y1 = tensor @ tensor.T
print(y1.shape)

torch.Size([2, 5])
torch.Size([5, 2])
torch.Size([2, 2])


- (m by n)  *  (n by m) 형식을 지켜야한다.

아래는 point-wise 곱, 즉 동일하게 대응되는 각각의 원소끼리의 연산을 나타낸다.

In [31]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

`-` In-place operation:  
In-place operation이란 주어진 tensor의 내용물을 copy없이 직접적으로 바꾸는 것을 의미한다.
- In-place operation의 예시로 `+=`나 `*=`와 같은 것들이 있다고 한다. 
- 출처: https://discuss.pytorch.org/t/what-is-in-place-operation/16244

Pytorch에서 In-place operation은 `_`를 뒤에 붙임으로써 사용된다 한다.
- 예: `x.copy_(y)`, `x.t_()`는 x를 변경한다.

아래의 예는 `tensor = ~~` 형태가 아님에도 함수 실행으로 tensor값을 바꾼다.

In [32]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


`-` Numpy와의 연결점  
`CPU 상에 있는 Tensor`와 Numpy는 이들의 memory location(?)을 공유할 수 있고, 하나를 바꾸면 다른 하나도 바뀐다 한다.

In [36]:
t = torch.ones(5)
print("t: ",t)
n = t.numpy()
print("n: ",n)


t:  tensor([1., 1., 1., 1., 1.])
n:  [1. 1. 1. 1. 1.]


이제 t라는 tensor를 바꾸면, t에서 파생된 numpy array인 n도 바뀌는 것을 보자

In [37]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


`-` Numpy array에서 Tensor로의 변환

In [41]:
n = np.ones(5)
t = torch.from_numpy(n)

이것도 마찬가지로, numpy array의 변화는 numpy array에서 나온 tensor 값 역시 변화시킨다.

In [43]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
n: [3. 3. 3. 3. 3.]
